.github/ISSUE_TEMPLATE/feature_request.md
=> Drew alexander98 [ISSUE] -> [FEATURE]

.eslintrc.json, src/mongoose.js, src/services/activity/activity.hooks.js, src/services/activity/activity.service.js, src/services/admin/admin.hooks.js, src/services/admin/admin.service.js, src/services/coach/coach.hooks.js, src/services/coach/coach.service.js, src/services/manager/manager.hooks.js, src/services/manager/manager.service.js, src/services/program/program.hooks.js, src/services/program/program.service.js, src/services/region/region.hooks.js, src/services/region/region.service.js, src/services/report/report.hooks.js, src/services/report/report.service.js, src/services/school/school.hooks.js, src/services/school/school.service.js, src/services/session/session.hooks.js, src/services/session/session.service.js, src/services/student/student.hooks.js, src/services/student/student.service.js
Adds a seeded admin
Some routes have been added to admin that make it a tad easier
fixes #24 
fixes #16 
fixes #8
=> Mongoose dev

src/hooks/permission.js, test/hooks/permission.test.js
=> added a permissions hook that can be added anywhere in the app

.travis.yml, README.md, jest.config.js, package.json
fixes #25 
fixes #31 
fixes #30
=> Badges and travis integration

src/hooks/userhooks.js, src/index.js, src/services/admin/admin.hooks.js, src/services/coach/coach.hooks.js, src/services/manager/manager.hooks.js, src/services/student/student.hooks.js
Moved admin model input and find code to generic hook which is referenced by the Manager, Admin, Coach and Student.
=> Generic user hook fixed #23

src/models/coach.model.js
Managers now have an array of coached they own. Coaches are related to managers through region only now
=> Changed manager coach relation to be one way bound

src/hooks/permission.js, src/hooks/userhooks.js, src/services/users/users.hooks.js
Adds a hook that allows blocking for user entities, while allowing the server
=> Fez userblock

src/hooks/userhooks.js, src/services/admin/admin.hooks.js, src/services/coach/coach.hooks.js, src/services/manager/manager.hooks.js, src/services/student/student.hooks.js
- Added generic function to combine data from users which is called in Userget and Userfind.
- Added calls to userfind and userget in manager, admin and coach hooks.
- Added password protection to hooks
- Rearranged functions in userhooks.js to reflect the query order in hook files
- Updated comments and removed options = {} from functions in userhooks.js
=> Added Userget

src/services/regions/regions.hooks.js
Set permissions for the region service
Admins can do all
Managers and coaches can only do things from there region
closes #60 
closes #64
=> Fez region perms

src/hooks/userhooks.js, src/services/users/coach.hooks.js, src/services/users/manager.hooks.js, src/services/users/users.service.js
Created limitQuery function to limit the query's for admin, manager and coach. 
Created manager service.
closes #62 
closes #61
=> Fez seperate users

src/hooks/userhooks.js
=> Removed userblock

src/models/users.model.js
=> Added feedback

src/hooks/permission.js
=> closes #75

src/models/users.model.js, src/services/regions/regions.hooks.js, src/services/users/coach.hooks.js
Automatically adds managers region to coach on creation.
Fixes #65
=> Auto coach region added

src/models/users.model.js
Removed required prop from user model to allow invite system to work
Fixes #85
=> remove user required

src/services/index.js
Changed wrong error code and updated seed
=> super seed update

src/services/users/coach.hooks.js, src/services/users/users.hooks.js
Reordered the hash password function in the hooks to come first for consistency.
=> coach and user permissions order change

src/services/users/manager.hooks.js
=> Fixd manager perms

src/channels.js
Changed elongated channel message, including feathers website plug to something more acceptable.
=> Reduce channel spam

src/seeder.js
God is dead, and we have killed him
=> God is dead

src/seeder.js, src/services/users/admin.hooks.js
Changed seeder a little to make the test admin all three roles.
Fixes #107
=> Test admin can be manager and admin

src/seeder.js
This avoids a bug when creating coaches as all managers need a region when doing so.
=> Added region to test admin

src/app.hooks.js, src/services/activities/activities.hooks.js, src/services/feedback/feedback.hooks.js, src/services/matrix/matrix.hooks.js, src/services/programs/programs.hooks.js, src/services/regions/regions.hooks.js, src/services/reports/reports.hooks.js, src/services/schools/schools.hooks.js, src/services/sessions/sessions.hooks.js, src/services/students/students.hooks.js, src/services/users/coach.hooks.js, src/services/users/manager.hooks.js, src/services/users/users.hooks.js
=> Hook permissions and update blocking

.travis.yml, package.json
=> Changed node version requirements
